ALTER TABLE products ADD COLUMN IF NOT EXISTS package_width INTEGER;
ALTER TABLE products ADD COLUMN IF NOT EXISTS package_height INTEGER;
ALTER TABLE products ADD COLUMN IF NOT EXISTS package_depth INTEGER;